export const UCLA_BLUE_RGB = "39, 116, 174";
export const UCLA_DARKER_BLUE_RGB = "0, 85, 135";
export const UCLA_LIGHTER_BLUE_RGB = "139, 184, 232";
export const UCLA_LIGHTEST_BLUE_RGB = "218, 235, 254";

export type Donors = [name: string, link?: string][];

export const DONORS_21F_222: Donors = [
  ["James Chen", undefined],
  ["Ashley Sun", undefined],
  ["Mark Gross", undefined],
  ["William Yao", undefined],
  ["Olive Long", undefined],
  ["Anonymous", undefined],
  ["Tian Ouyang", undefined],
  ["Sammy Fesili", undefined],
  ["Khang Nguyen Le Tuan", undefined],
  ["Casey T", undefined],
  ["Gabriel Soulman", undefined],
  ["Manseej Khatri", undefined],
  ["Christopher Milan", undefined],
  ["Kevin Tran", undefined],
  ["Mallesh Dhamodran", undefined],
  ["Rory Kien", undefined],
  ["Samuel Leistiko", undefined],
  ["Preston Rooker", undefined],
  ["Cassidy Ott", undefined],
  ["Alex Rojas", undefined],
  ["Aiden Gresham", undefined],
  ["Erin Su", undefined],
  ["Tiffany Chen", undefined],
  ["Gage Green", undefined],
  ["Akane Shimoyoshi", undefined],
  ["Alex Lebow", undefined],
  ["Xiaoyang Liu", undefined],
  ["Rahul Sathish", undefined],
  ["James Snyder", undefined],
  ["Hayley Vu", undefined],
  ["Rujula Rao", undefined],
  ["Brandon Zhao", undefined],
  ["Ashley Tohm", undefined],
  ["Ryan Schoenburg", undefined],
  ["Ryan Zdral", undefined],
  ["Jason M", undefined],
  ["Joshua Lim", undefined],
  ["Elaine Tran", undefined],
  ["Jiexuan Fang", undefined],
  ["A O", undefined],
  ["Alec Machlis", undefined],
  ["Ryan Chow", undefined],
  ["Michelle Kim", undefined],
  ["Natalie Brown", undefined],
  ["Michelle Sun", undefined],
  ["Kevin Tang", undefined],
];

export const DONORS_22F_23S: Donors = [
  ["Anonymous", undefined],
  ["Anonymous", "https://youtu.be/JfJsVhiLL8o?si=UWXKkHvljVCuPPDo"],
  ["Mark Gross", undefined],
  ["Christopher Milan", undefined],
  ["Angel Armendariz", undefined],
  ["Omar Elamri", undefined],
  ["Joshua Lim", undefined],
  ["Nick Monozon", undefined],
  ["Christopher Tran", undefined],
  ["Charles Long", undefined],
  ["Aidan Byer", undefined],
  ["Celine Park", undefined],
  ["Samuel Leistiko", undefined],
  ["Milo", undefined],
  ["Nitin Dhami", undefined],
  ["Dean Mac", undefined],
  ["Teela Hamner", undefined],
  ["no shoutout for me pls", undefined],
  ["Kevin Tran", undefined],
  ["Maxine Wu", undefined],
  ["Siddharth Bid", undefined],
  ["Eric Estrada", undefined],
  ["Sonal Aggarwal", undefined],
  ["Anonymous", undefined],
  ["Jason An", undefined],
  ["Justin He", undefined],
];

export const DONORS_241_25S: Donors = [
  ["Anonymous", undefined],
  ["Justin Chai", undefined],
  ["Mikayla Silva", undefined],
  ["Tiffany Pe", undefined],
  ["Ryland Goldman", undefined],
  ["Raayan Dhar", undefined],
  ["Daniel Bai", undefined],
  ["Anonymous", undefined],
  ["Anonymous", undefined],
  ["Edmond Wang", undefined],
  ["Anonymous", undefined],
  ["Albert Dong", undefined],
  ["Rosie o", undefined],
  ["Arya Gharib", undefined],
  ["Anonymous", undefined],
  ["Anonymous", undefined],
  ["Rebecca Lee", undefined],
  ["Eric Mai", undefined],
  ["Serena Mehta", undefined],
  ["Joseph Zhang", undefined],
  ["Anonymous", undefined],
  ["Shawn Vu", undefined],
  ["Jiahong Chen", undefined],
  ["Anonymous", undefined],
  ["Anonymous", undefined],
  ["Viraj Chandra", undefined],
  ["Aidan Chan", undefined],
  ["Edmund Leong", undefined],
  ["Anonymous", undefined],
  ["Kunal Singhal", undefined],
  ["Aadrij Upadya", undefined],
  ["Angela Zhang", undefined],
  ["Anonymous", undefined],
  ["Eric Lu", undefined],
  ["Ryan Booher", undefined],
  ["Mahan Pourfakhr", undefined],
  ["Zilu Yi", undefined],
  ["Shelli Orzach", undefined],
  ["Sonal Aggarwal", undefined],
  ["Gabriel Castro", undefined],
  ["esha", undefined],
  ["Anonymous", undefined],
  ["Anonymous", undefined],
];
